/* 
 * Default/18.200.001
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Acumatica.RESTClient.Client.OpenAPIDateConverter;

namespace Acumatica.DefaultEndpoint.Model
{
    /// <summary>
    /// ProjectTemplateTaskProperties
    /// </summary>
    [DataContract]
    public partial class ProjectTemplateTaskProperties : Entity,  IEquatable<ProjectTemplateTaskProperties>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectTemplateTaskProperties" /> class.
        /// </summary>
        /// <param name="approver">approver.</param>
        /// <param name="automaticallyIncludeInProject">automaticallyIncludeInProject.</param>
        /// <param name="completionMethod">completionMethod.</param>
        /// <param name="_default">_default.</param>
        public ProjectTemplateTaskProperties(StringValue approver = default(StringValue), BooleanValue automaticallyIncludeInProject = default(BooleanValue), StringValue completionMethod = default(StringValue), BooleanValue _default = default(BooleanValue), Guid? id = default(Guid?), long? rowNumber = default(long?), string note = default(string), Dictionary<string, Dictionary<string, CustomField>> custom = default(Dictionary<string, Dictionary<string, CustomField>>), List<FileLink> files = default(List<FileLink>)) : base(id, rowNumber, note, custom, files)
        {
            this.Approver = approver;
            this.AutomaticallyIncludeInProject = automaticallyIncludeInProject;
            this.CompletionMethod = completionMethod;
            this.Default = _default;
        }
        
        /// <summary>
        /// Gets or Sets Approver
        /// </summary>
        [DataMember(Name="Approver", EmitDefaultValue=false)]
        public StringValue Approver { get; set; }

        /// <summary>
        /// Gets or Sets AutomaticallyIncludeInProject
        /// </summary>
        [DataMember(Name="AutomaticallyIncludeInProject", EmitDefaultValue=false)]
        public BooleanValue AutomaticallyIncludeInProject { get; set; }

        /// <summary>
        /// Gets or Sets CompletionMethod
        /// </summary>
        [DataMember(Name="CompletionMethod", EmitDefaultValue=false)]
        public StringValue CompletionMethod { get; set; }

        /// <summary>
        /// Gets or Sets Default
        /// </summary>
        [DataMember(Name="Default", EmitDefaultValue=false)]
        public BooleanValue Default { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProjectTemplateTaskProperties {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Approver: ").Append(Approver).Append("\n");
            sb.Append("  AutomaticallyIncludeInProject: ").Append(AutomaticallyIncludeInProject).Append("\n");
            sb.Append("  CompletionMethod: ").Append(CompletionMethod).Append("\n");
            sb.Append("  Default: ").Append(Default).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProjectTemplateTaskProperties);
        }

        /// <summary>
        /// Returns true if ProjectTemplateTaskProperties instances are equal
        /// </summary>
        /// <param name="input">Instance of ProjectTemplateTaskProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProjectTemplateTaskProperties input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Approver == input.Approver ||
                    (this.Approver != null &&
                    this.Approver.Equals(input.Approver))
                ) && base.Equals(input) && 
                (
                    this.AutomaticallyIncludeInProject == input.AutomaticallyIncludeInProject ||
                    (this.AutomaticallyIncludeInProject != null &&
                    this.AutomaticallyIncludeInProject.Equals(input.AutomaticallyIncludeInProject))
                ) && base.Equals(input) && 
                (
                    this.CompletionMethod == input.CompletionMethod ||
                    (this.CompletionMethod != null &&
                    this.CompletionMethod.Equals(input.CompletionMethod))
                ) && base.Equals(input) && 
                (
                    this.Default == input.Default ||
                    (this.Default != null &&
                    this.Default.Equals(input.Default))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Approver != null)
                    hashCode = hashCode * 59 + this.Approver.GetHashCode();
                if (this.AutomaticallyIncludeInProject != null)
                    hashCode = hashCode * 59 + this.AutomaticallyIncludeInProject.GetHashCode();
                if (this.CompletionMethod != null)
                    hashCode = hashCode * 59 + this.CompletionMethod.GetHashCode();
                if (this.Default != null)
                    hashCode = hashCode * 59 + this.Default.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
